blank_issues_enabled: false
contact_links:
  - name: FreeShow Bug Report
    url: https://github.com/ChurchApps/FreeShow/issues/new?template=bug_report.md
    about: Help us improve the stability of FreeShow
  - name: FreeShow Feature Request
    url: https://github.com/ChurchApps/FreeShow/issues/new?template=feature_request.md
    about: Suggest a new feature/improvement for FreeShow